apiVersion: v1
kind: BuildConfig
metadata:
  name: nodejs-8
spec:
  triggers:
    - type: ConfigChange
    - type: ImageChange
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: ''
      ref: master
    sourceSecret:
      name: deployment-key
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: rhel-atomic:latest
      env:
        - name: NODE_VERSION
          value: 8.2.1
      noCache: true
  output:
    to:
      kind: ImageStreamTag
      name: 'nodejs-8:latest'
