apiVersion: v1
kind: BuildConfig
metadata:
  name: nodejs-6-s2i
spec:
  triggers:
    - type: ConfigChange
    - type: ImageChange
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: ''
      ref: master
    sourceSecret:
      name: deployment-key
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile.s2i
      from:
        kind: ImageStreamTag
        name: nodejs-6:latest
      noCache: true
  output:
    to:
      kind: ImageStreamTag
      name: 'nodejs-6-s2i:latest'
